bookers2-debug/config/routes.rb
Rails.application.routes.draw do
    root 'home#top'
    get 'home/about' => 'home#about'
    devise_for :users
    resources :users
    resources :books do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
    end
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :show, :index]
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get 'users/following/:user_id' => 'users#following', as:'users_following'
    get 'users/follower/:user_id' => 'users#follower', as:'users_follower'
    get "search" => "search#search"
end

bookers2-debug/app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
    validates :body, presence: true, length: {maximum: 200}

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    def Book.search(search, user_or_book, how_search)
            if how_search == "1"
                Book.where(['title LIKE ?', "#{search}"])
            elsif how_search == "2"
                Book.where(['title LIKE ?', "#{search}%"])
            elsif how_search == "3"
                Book.where(['title LIKE ?', "%#{search}"])
            elsif how_search == "4"
                Book.where(['title LIKE ?', "%#{search}%"])
            else
                Book.all
            end
        end
end

bookers2-debug/app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :set_book, only: [:show, :edit, :update, :destroy]

  def show
      @comment = Comment.new
      @comments = @book.comments
  end

  def index
	@book = Book.new
  	@books = Book.all.order(created_at: :desc) #一覧表示するためにBookモデルの情報を全てくださいのall
  end

  def create
    @book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  	    redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
	  unless @book.user == current_user
		redirect_to books_path
	  end
  end

  def update
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
	end

	def set_book
		@book = Book.find(params[:id])
	end
	
end

bookers2-debug/app/helpers/books_helper.rb
module BooksHelper
end

bookers2-debug/app/views/books/_books.html.erb
<% books.each do |book| %>
    <tr>
        <td>
            <%= link_to(book.user) do %>
            <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
            <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td class="favoritebutton_<%= book.id %>">
            <%= render 'books/favoritebutton', book: book %>
        </td>
        <td>コメント数 : <%= book.comments.count %></td>
    </tr>
<% end %>

bookers2-debug/app/views/books/_comments.html.erb
<% comments.each do |comment| %>
    <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user.name %></td>
        <td>
            <% if comment.user == current_user %>
            <%= link_to "Destroy", book_comment_path(@book,comment), method: :delete, class: "btn-sm btn-danger", remote: true %>
            <% end %>
        </td>
    </tr>
<% end %>

bookers2-debug/app/views/books/_favoritebutton.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %>
    <% end %>
<% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <%= book.favorites.count %>
    <% end %>
<% end %>

bookers2-debug/app/views/books/_newform.html.erb
<% if book.errors.any? %>
<h2><%= book.errors.count %>error</h2>
<div>
	<ul>
		<% book.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

bookers2-debug/app/views/books/create.js.erb
$("textarea").val('');
$(".new_book").html("<%= j(render 'books/books', books: @books) %>");

bookers2-debug/app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

bookers2-debug/app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th>Likes</th>
                    <th>Comments</th>
				</tr>
			</thead>

			<tbody class="new_book">
                <%= render 'books', books: @books %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

bookers2-debug/app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
            <tr>
                <td>
                    <%= link_to(@book.user) do %>
                    <%= attachment_image_tag(@book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
                    <% end %>
                </td>
                <td><%= link_to @book.title, book_path(@book), class: "book_#{@book.id}" %></td>
                <td><%= @book.body %></td>
                <td class="favoritebutton_<%= @book.id %>">
                    <%= render 'books/favoritebutton', book: @book %>
                </td>
                <td>コメント数 : <%= @book.comments.count %></td>
                <% if @book.user == current_user %>
                    <td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
                    <td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
                <% end %>
            </tr>
        </table>

        <table class="table">
            <thead>
                <tr>
                    <th>comment</th>
                    <th>name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="new_comment">
                    <%= render 'comments', comments: @comments %>
            </tbody>
        </table>

        <%= form_with(model: [@book, @comment], remote: true) do |f| %>
            <%= f.text_area :body, size: "120x10" %>
            <%= f.submit "送信" %>
        <% end %>
	</div>
</div>