bookers2-debug/config/routes.rb
Rails.application.routes.draw do
    root 'home#top'
    get 'home/about' => 'home#about'
    devise_for :users
    resources :users
    resources :books do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
    end
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :show, :index]
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get 'users/following/:user_id' => 'users#following', as:'users_following'
    get 'users/follower/:user_id' => 'users#follower', as:'users_follower'
    get "search" => "search#search"
end

bookers2-debug/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }

  geocoded_by :address_city
  after_validation :geocode

  def favorited_by?(book)
    favorites.where(book_id: book.id).exists?
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    following_user.include?(user)
  end

    def User.search(search, user_or_book, how_search)
        if user_or_book == "1"
            if how_search == "1"
                User.where(['name LIKE ?', "#{search}"])
            elsif how_search == "2"
                User.where(['name LIKE ?', "#{search}%"])
            elsif how_search == "3"
                User.where(['name LIKE ?', "%#{search}"])
            elsif how_search == "4"
                User.where(['name LIKE ?', "%#{search}%"])
            else
                User.all
            end
        end
    end

    include JpPrefecture
    jp_prefecture :prefecture_code

    def prefecture_name
        JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
    end

    def prefecture_name=(prefecture_name)
        self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
    end
end

bookers2-debug/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
    @book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
	  @user = User.find(params[:id])
	  unless @user == current_user
		redirect_to user_path(current_user)
	  end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  def following
    @user = User.find(params[:user_id])
  end

  def follower
    @user = User.find(params[:user_id])
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

bookers2-debug/app/helpers/users_helper.rb
module UsersHelper
end

bookers2-debug/app/views/users/_followbutton.html.erb
<% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST,class:"btn btn-info", remote: true %>
<% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST,class:"btn btn-default", remote: true %>
<% end %>

bookers2-debug/app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

		<tr>
			<th>follows</th>
			<th><%= link_to "#{user.follower.count}", users_following_path(user) %></th>
		</tr>

		<tr>
			<th>followers</th>
			<th><%= link_to "#{user.followed.count}", users_follower_path(user) %></th>
		</tr>

        <tr>
            <th class="followbutton_<%= user.id %>">
                <% unless user == current_user %>
                    <%= render "followbutton", user: user %>
                <% end %>
            </th>
            <th></th>
		</tr>

        <tr>
            <th>
                <% if user.id == current_user.id %>

                <% else %>
                <% if @isRoom == true %>
                    <p><a href="/rooms/<%= @roomId %>">チャットへ</a>
                <% else %>
                    <%= form_for @room do |f| %>
                    <%= fields_for @entry do |e| %>
                        <%= e.hidden_field :user_id, :value=> user.id %>
                    <% end %>
                    <%= f.submit "チャットを始める",class:"btn btn-default" %>
                    <% end %>
                <% end %>
                <% end %>
            </th>
            <th></th>
        </tr>
</table>

<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

bookers2-debug/app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :profile_image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

bookers2-debug/app/views/users/follower.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-2"></div>
		<div class="col-xs-8">
			<h3>フォロー中</h3>
			<table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Introduction</th>
                        <th></th>
                    </tr>
                </thead>
				<tbody>
					<% @user.follower_user.where.not(id: current_user.id).each do |user| %>
						<tr class="followbutton_<%= user.id %>">
	                		<%= render "follow", user: user %>
	                	</tr>
					<% end %>
				</tbody>
			</table>
		</div>
        <div class="col-xs-2"></div>
	</div>
</div>

bookers2-debug/app/views/users/following.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-2"></div>
		<div class="col-xs-8">
			<h3>フォロー中</h3>
			<table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Introduction</th>
                        <th></th>
                    </tr>
                </thead>
				<tbody>
					<% @user.following_user.where.not(id: current_user.id).each do |user| %>
                        <tr>
                            <%= link_to user_path(user) do %>
                                <td><%= attachment_image_tag user, :profile_image, :size =>'30x30', class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %></td>
                                <td><%= user.name %></td>
                                <td><%= user.introduction %></td>
                            <% end %>
                            <td class="followbutton_<%= user.id %>">
                                <%= render "followbutton", user: user %>
                            </td>
                        </tr>
					<% end %>
				</tbody>
			</table>
		</div>
        <div class="col-xs-2"></div>
	</div>
</div>

bookers2-debug/app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->
			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
		</div>
		<div class="col-xs-9">
			<h2>Users</h2>
			<!--users一覧 -->
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
                        <th colspan="3"></th>
                        <th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name%></td>
						<td><%= link_to "Show", user %></td>
                        <td><%= link_to "フォロー数:#{user.follower.count}", users_following_path(user) %></td>
                        <td><%= link_to "フォロワー数:#{user.followed.count}", users_follower_path(user) %></td>
                        <td class="followbutton_<%= user.id %>">
                            <% unless user == current_user %>
                                <%= render "followbutton", user: user %>
                            <% end %>
                        </td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<!--users一覧 -->
		</div>
	</div>
</div>

bookers2-debug/app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to book.user do %>
						<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg" %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
    <% if @user == current_user %>
        <h2>gmap</h2>
        <div id='map'></div>

        <style>
        #map {
        height: 600px;
        width: 600px;
        }
        </style>

        <script>
        let map

        function initMap(){
        geocoder = new google.maps.Geocoder()

        map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: <%= @user.latitude %>, lng: <%= @user.longitude %>},
            zoom: 12,
        });

        marker = new google.maps.Marker({
            position:  {lat: <%= @user.latitude %>, lng:<%= @user.longitude %>},
            map: map
        });
        }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap" async defer></script>
    <% end %>
</div>