bookers2-debug/config/routes.rb
Rails.application.routes.draw do
    root 'home#top'
    get 'home/about' => 'home#about'
    devise_for :users
    resources :users
    resources :books do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
    end
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :show, :index]
    post 'follow/:id' => 'relationships#follow', as: 'follow'
    post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
    get 'users/following/:user_id' => 'users#following', as:'users_following'
    get 'users/follower/:user_id' => 'users#follower', as:'users_follower'
    get "search" => "search#search"
end

bookers2-debug/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2-debug/app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :comments, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
    validates :body, presence: true, length: {maximum: 200}

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    def Book.search(search, user_or_book, how_search)
            if how_search == "1"
                Book.where(['title LIKE ?', "#{search}"])
            elsif how_search == "2"
                Book.where(['title LIKE ?', "#{search}%"])
            elsif how_search == "3"
                Book.where(['title LIKE ?', "%#{search}"])
            elsif how_search == "4"
                Book.where(['title LIKE ?', "%#{search}%"])
            else
                Book.all
            end
        end
end

bookers2-debug/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :book

    validates :body, presence: true
end

bookers2-debug/app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

bookers2-debug/app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

bookers2-debug/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

bookers2-debug/app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

bookers2-debug/app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

bookers2-debug/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }

  geocoded_by :address_city
  after_validation :geocode

  def favorited_by?(book)
    favorites.where(book_id: book.id).exists?
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    following_user.include?(user)
  end

    def User.search(search, user_or_book, how_search)
        if user_or_book == "1"
            if how_search == "1"
                User.where(['name LIKE ?', "#{search}"])
            elsif how_search == "2"
                User.where(['name LIKE ?', "#{search}%"])
            elsif how_search == "3"
                User.where(['name LIKE ?', "%#{search}"])
            elsif how_search == "4"
                User.where(['name LIKE ?', "%#{search}%"])
            else
                User.all
            end
        end
    end

    include JpPrefecture
    jp_prefecture :prefecture_code

    def prefecture_name
        JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
    end

    def prefecture_name=(prefecture_name)
        self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
    end
end

bookers2-debug/app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :set_book, only: [:show, :edit, :update, :destroy]

  def show
      @comment = Comment.new
      @comments = @book.comments
  end

  def index
	@book = Book.new
  	@books = Book.all.order(created_at: :desc) #一覧表示するためにBookモデルの情報を全てくださいのall
  end

  def create
    @book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  	    redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
	  unless @book.user == current_user
		redirect_to books_path
	  end
  end

  def update
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
	end

	def set_book
		@book = Book.find(params[:id])
	end
	
end

bookers2-debug/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

bookers2-debug/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2-debug/app/helpers/books_helper.rb
module BooksHelper
end

bookers2-debug/app/helpers/comments_helper.rb
module CommentsHelper
end

bookers2-debug/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2-debug/app/helpers/home_helper.rb
module HomeHelper
end

bookers2-debug/app/helpers/messages_helper.rb
module MessagesHelper
end

bookers2-debug/app/helpers/rooms_helper.rb
module RoomsHelper
end

bookers2-debug/app/helpers/search_helper.rb
module SearchHelper
end

bookers2-debug/app/helpers/users_helper.rb
module UsersHelper
end

bookers2-debug/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/c51513dd6c.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <!--ヘッダーの記述-->
    <div class="container">
        <% if user_signed_in? %>
            <%= form_tag(search_path, :method => 'get',class: "search_form") do %>
                <%= text_field_tag :search %>
                <%= select_tag(:option, options_for_select([["user", "1"],["book","2"]]))%>
                <%= select_tag(:choice, options_for_select([["完全一致", "1" ],["前方一致", "2" ],["後方一致", "3" ],["部分一致", "4" ]])) %>
                <%= submit_tag 'Search' %>
            <% end %>
        <% end %>
        <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->
        <%= yield %>
    </div>
  </body>
</html>